import { Review } from './review';
//utilisation du mock à nouveau, le node js c'est bien mais pas sur un serveur mutualisé...
export const REVIEWS: Review[] = [

	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////PPV/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////


	{
		id:14,
		name: "WWE TLC 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1qUQkxf7u_jQBItkxgw89fUwjJQzgABoaAJnFFo4mZTs/edit?usp=sharing",
		img:"WWE",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Hell In A Cell 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1JMhfPgYer2qA4PZj47CRTPTxyJLNgNG_ZOie5WKvhBM/edit#heading=h.wiv8pkhqgdxz",
		img:"WWE",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
  {
    id: 15,
    name: "NXT TakeOver UK : Blackpool",
    date: new Date(),
    year: null,
    driveLink: "https://docs.google.com/document/d/1xM1_Go9C-yyX0B4Iuk_jeqsy-RdmHzzSjQWU2VsBFn8",
    img: "NXTUK",
    type: "WWE PPV",
    types: ["WWE", "NXT UK"],
  },
  {
    id: 16,
    name: "NXT TakeOver : Phoenix",
    date: new Date(),
    year: null,
    driveLink: "https://docs.google.com/document/d/18y7rWDADBFub_oC8rU85kkW_zSKNdvYJGeYeYltL3lk",
    img: "NXT",
    type: "WWE PPV",
    types: ["WWE", "NXT"],
  },
  {
    id: 17,
    name: "WWE Royal Rumble 2019",
    date: new Date(),
    year: null,
    driveLink: "https://docs.google.com/document/d/1YqmPHbSBA-mgcJ2vSxUQiuJFmOsw4Jm1B3G2p7YwZII",
    img: "WWE",
    type: "WWE PPV",
    types: ["WWE", "PPV"],
  },
		////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////LISTES ET BILANS////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:401,
		name: "Les 4* 2019",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1smdDhBc_9jAQiACMtjM2QWOJAVKDfWTIa61euKsdj0I",
		img:"4starslist",
		type:"Liste 4*+",
		types: ["Liste 4*+"],
	},
	{
		id:402,
		name: "Les 4* 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1Kcpzcil3QecaY4JGnD8FYBt8OS-qsQfBICFQlgWj-2c/edit?usp=sharings",
		img:"4starslist",
		type:"Liste 4*+",
		types: ["Liste 4*+"],
	},
	{
		id:403,
		name: "Les 4* 2017",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/12Fp7ouasm_vaSRh00mRjXLFzvKYZ1zIqxPNZ5s5GyDU",
		img:"4starslist",
		type:"Liste 4*+",
		types: ["Liste 4*+"],
	},
	{
		id:404,
		name: "Bilan 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1vSCsWTp9K5smYLVXKS4zIq70pfR0izGznk-pa3qdyAo",
		img:"4starslist",
		type:"Bilan",
		types: ["Bilan"],
	},	
	{
		id:405,
		name: "Bilan mi parcours 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/14KMNmUIqUn0-dsLLB5EcKfumtN-S5ZPgllEBpoggG-s/edit?usp=sharing",
		img:"4starslist",
		type:"Bilan",
		types: ["Bilan"],
	},
	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////MIX 2018////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////


	{
		id:11,
		name: "NJPW 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1WlZ_5zcflboPzuKFzMWMruOetdFdbRRuo6S0Sy4WrAg/edit",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW"],
	},
	{
		id:11.1,
		name: "NJPW 2019",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1smdDhBc_9jAQiACMtjM2QWOJAVKDfWTIa61euKsdj0I",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW"],
	},
	{
		id:12,
		name: "NJPW BOSJ 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1310NlpB9UMBDdNG_Bgd_VgP9QHCRpoM9dSynxuPDXAA/edit",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW", "BOSJ"],
	},
	{
		id:10,
		name: "NJPW G1 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1KoZix0UoTCiLBehLlCgN12cm0-wl3q7ATjTc0ziDO8Q/edit",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW", "G1"]
	},
	{
		id:9,
		name: "IMPACT 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1MmrjdV7u3C889Q208JQRAs2KPhG8u1wLEkX2xGdqdZQ/edit",
		img:"IMPACT",
		type:"IMPACT",
		types: ["IMPACT"],
	},
	{
		id:8,
		name: "Jap 2018 : AJPW NOAH Dragon Gate DDT BJW",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1RuTip2OduveqHkmTTGe-pr1sa3hbUYDhdvqDkZcfBRY/edit",
		img:"JAP",
		type:"JAP",
		types: ["JAP"],
	},
	{
		id:7,
		name: "PROGRESS 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1xyJzOJQbHiaBjcT3-Q3oOthE5gJuLkmy9dcd25yS3Do/edit",
		img:"PROGRESS",
		type:"INDÉ",
		types: ["INDÉ", "PROGRESS"],
	},
	{
		id:6,
		name: "ROH 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1uFLYDA4G-CXz-qjODfCgZ_KE5b8XmUlvI07QhVenKgs/edit",
		img:"ROH",
		type:"ROH",
		types: ["ROH"],
	},
	{
		id:5,
		name: "PWG 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1dw0jrt6UCYQcK3qkt88IC7ZCdb_2ajtr-xG0Q8CeFvI/edit",
		img:"PWG",
		type:"PWG",
		types: ["PWG"],
	},
	{
		id:4,
		name: "WWE NXT UK 2018",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/11SAq9SWSwlNvcqWVV0FsnALhHe3fw4xCe4b2YYmRAY4/edit",
		img:"NXTUK",
		type:"WWE NXT",
		types: ["WWE", "NXT UK"],
	},
	{
		id:3,
		name: "Indé 2018 wXw EVOLVE GCW DEFIANT IWA ALL IN",
		date: new Date(),
		year: null,
		driveLink:"https://docs.google.com/document/d/1ZjOGVs-pq62lqF-67taJqPyCG152RGPKMqJ7GFE0WXE/edit",
		img:"INDÉ",
		type:"INDÉ",
		types: ["INDÉ"],
	},


]
