import { Review } from './review';
//utilisation du mock à nouveau, le node js c'est bien mais pas sur un serveur mutualisé...
export const REVIEWS: Review[] = [
	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////WWE 2019/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
  {
    id: 15,
    name: "NXT TakeOver UK : Blackpool",
    date: 2019,
    driveLink: "https://docs.google.com/document/d/1xM1_Go9C-yyX0B4Iuk_jeqsy-RdmHzzSjQWU2VsBFn8",
    img: "NXTUKBP",
    type: "WWE NXT",
    types: ["WWE", "NXT UK"],
  },
  {
    id: 16,
    name: "NXT TakeOver : Phoenix",
    date: 2019,
    driveLink: "https://docs.google.com/document/d/18y7rWDADBFub_oC8rU85kkW_zSKNdvYJGeYeYltL3lk",
    img: "NXTPHOENIX",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	
  {
    id: 16,
    name: "NXT TakeOver : New York",
    date: 2019,
    driveLink: "hhttps://docs.google.com/document/d/101Q35HWN5aB9szH9pP5_ffMid403UemtVQBB5uPSskk",
    img: "NXTNY",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	
  {
    id: 16,
    name: "NXT TakeOver : XXV",
    date: 2019,
    driveLink: "https://docs.google.com/document/d/1EJxrpyOPpjtUWGfKf1_CywFx1fvLgawFQr25B5St99Y",
    img: "NXTXXV",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
},
{
    id: 16,
    name: "NXT TakeOver : Toronto 2",
    date: 2019,
    driveLink: "https://docs.google.com/document/d/10q4pj5R-BW3_KiNLWXQNZSEoJEC7lxMTh40RZ3Yukp0",
    img: "NXTTORONTO",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
},
  {
    id: 17,
    name: "WWE Royal Rumble 2019",
    date: 2019,
    driveLink: "https://docs.google.com/document/d/1YqmPHbSBA-mgcJ2vSxUQiuJFmOsw4Jm1B3G2p7YwZII",
    img: "WWERR",
    type: "WWE PPV",
    types: ["WWE", "PPV"],
},
{
	id:14,
	name: "WWE Super Show Down 2019",
	date: 2019,
	driveLink:"https://docs.google.com/document/d/1O_p0pLHlJ_CzHP2d81FeLhuQHHNL6tQGfKUECLrUo_w",
	img:"WWESSD2",
	type:"WWE PPV",
	types: ["WWE", "PPV"],
},
{
	id:14,
	name: "WWE Stomping Ground 2019",
	date: 2019,
	driveLink:"https://docs.google.com/document/d/1rtDqlu8_43MM7a46eFo817yLp2YwIMm_50cGA2KNChE",
	img:"STOMPING",
	type:"WWE PPV",
	types: ["WWE", "PPV"],
},
      {
        id: 17,
        name: "WWE Fastlane 2019",
        date: 2019,
        driveLink: "https://docs.google.com/document/d/1EuhjtCvpLM-AzFE65srbHWFJ5I0CzuAhouNgmExMfIU",
        img: "WWEFASTLANE",
        type: "WWE PPV",
        types: ["WWE", "PPV"],
    },
{
  id: 18,
  name: "WWE Elimination Chamber 2019",
  date: 2019,
  driveLink: "https://docs.google.com/document/d/132uYp-K13sT33oaHN_rqaPWEQawf2syjw6A_vuY0yJY",
  img: "WWEEC",
  type: "WWE PPV",
  types: ["WWE", "PPV"],
},
{
  id: 19,
  name: "WWE Wrestlemania 35",
  date: 2019,
  driveLink: "https://docs.google.com/document/d/1K2YXyQGlXJta4yHcFyJqI4w6v9zFz8dJxPIsewkoIl4",
  img: "WWEWM35",
  type: "WWE PPV",
  types: ["WWE", "PPV"],
},
{
	id:14,
	name: "WWE Summerslam 2019",
	date: 2019,
	driveLink:"https://docs.google.com/document/d/1bqMQhNOMsPSINTxjqopa3Jvp2CVDtufmosHBH6_K28g",
	img:"WWESMS",
	type:"WWE PPV",
	types: ["WWE", "PPV"],
},
{
  id: 19,
  name: "WWE Money In The Bank 2019",
  date: 2019,
  driveLink: "https://docs.google.com/document/d/12D6iRmSL5kSoMTqwhOeomB9NxBMyWSeB0ZO4bn5Ifyc",
  img: "WWEMITB",
  type: "WWE PPV",
  types: ["WWE", "PPV"],
},
{
	id:14,
	name: "WWE Extreme Rules 2019",
	date: 2019,
	driveLink:"https://docs.google.com/document/d/1eVmqT3RE0nY-pJmgufvUtqX25CPY05UlymLygnULVDI",
	img:"WWEER",
	type:"WWE PPV",
	types: ["WWE", "PPV"],
},

{
	id:14,
	name: "WWE Clash Of Champions 2019",
	date: 2019,
	driveLink:"https://docs.google.com/document/d/1Sc0EtDV9VBQE81iTMe-8Wid_ThVV_dPY99DHUSw7ZpU",
	img:"WWECOC",
	type:"WWE PPV",
	types: ["WWE", "PPV"],
},

	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////WWE 2018/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////


	{
		id:14,
		name: "WWE TLC 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1qUQkxf7u_jQBItkxgw89fUwjJQzgABoaAJnFFo4mZTs/edit?usp=sharing",
		img:"WWETLC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Hell In A Cell 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1JMhfPgYer2qA4PZj47CRTPTxyJLNgNG_ZOie5WKvhBM/edit#heading=h.wiv8pkhqgdxz",
		img:"WWEHIAC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Greatest Royal Rumble",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1PLBwh9OJ-4_IN8yYlJMHEsNY2zcJ2-7h8NB4P2Fzhwk",
		img:"WWEGRR",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Super Show Down 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1aAzYz37RZMumWpB9dPvLImSrUY7IHHqe-8mmS6ckVWc",
		img:"WWESSD",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Wrestlemania 34",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1VFzbse1wxyoYk8qYgWyARXzOQhSqFESXXLc3jhZ_fTE",
		img:"WWEWM34",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Money In The Bank 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1XJMOL1wPeQyQ3j2PceDZdlCNfmxk9atPSfWuBRo9x3c",
		img:"WWEMITB",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Backlash 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1s85To3V0d8Fq4e4BCXA2u5s1Hvu1rye-Uv1xZM7jBO8",
		img:"WWEBC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Fastlane 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1452mrHMr1d-P6fueu6QSs9NLxbyrqbQfj6qkA5auU_A",
		img:"WWEFASTLANE",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Extreme Rules 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1t9vLsbgY9FU0xJPAeHxVwBpOXGl3KoMQhH8AimX1PYs",
		img:"WWEER",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Elimination Chamber 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1_rk9QGClT2aFiAono7pMcj05NyTsmDiW5JsmyLFzxHc",
		img:"WWEEC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Royal Rumble 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/155FOgZKEPv5daOtoVHAfSJ3f4_V9ZmU59wiCM1SN3So",
		img:"WWERR",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Evolution 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1F8Gq_XKo4Kc_AeOuVwkCwoUpi_btpEs3CD-fwE05Fow",
		img:"WWEEV",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Summerslam 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1TbIflvzkCS87jnBRWY1Fg4ELJ9P0bE9kDAkN-6PMHbA",
		img:"WWESMS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Survivor Series 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1v72ezYmIHlSBDGjw8ojXTUzGzG2gHMjn9g-WfJo05W4",
		img:"WWESS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	
	{
    id: 16,
    name: "NXT TakeOver : Philadelphia",
    date: 2018,
    driveLink: "https://docs.google.com/document/d/1EPpBA8LPk8ELEavufFk5-5pQd9I2H592edRQoiGhC0k",
    img: "NXTPHILADELPHIA",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	{
    id: 16,
    name: "NXT TakeOver : New Orlean",
    date: 2018,
    driveLink: "https://docs.google.com/document/d/1MJH9LhDIOTZrb4L4J25UTPfYoZURxDSaGOdb1y5dc10",
    img: "NXTNEWORLEAN",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	
		////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////WWE 2017/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:14,
		name: "WWE Backlash 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/141blpnEiX8rVVf0yGm2p3nPrxSgDeXfmT_Yr0IJjE4U",
		img:"WWEBC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Elimination Chamber 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1_SrIWHJv0bdsPaLZjdaH-S-qnF4Z5vpGj4c4Apob4mY",
		img:"WWEEC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Clash Of Champions 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1jPuU7Ez6-FSUpIwjdrr-7l7eTgiIzW7HUOCerh18y7E",
		img:"WWECOC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Battleground 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/10gNqQzGyoryu0OyQGosvzY6Y5fWo-bz2XDueD2hENS0",
		img:"WWEBG",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Extreme Rules 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1ibZ1432oDGm22PmJXeFCQJyf06Z_qfXHVfPYHZ4eB4A",
		img:"WWEER",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Fastlane 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1oEJ4KvK6vfGj9q7hXJMeOdNWo1G9aSl8Gznd9ccSECo",
		img:"WWEFASTLANE",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Great Balls Of Fire 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/10WiukPnG057Rm5GQ3rzlQyL5LGWAm5he06RXx75ATQk",
		img:"WWEGBOF",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Hell In A Cell 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/19xtMiEQzJidFq-VrC0OhT8ovF5yiFW3VSlwKnfIJnQM",
		img:"WWEHIAC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE No Mercy 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1dIwNfVqOhlftM84zo96CEAq3wekYO6xIgWABfvE5EjQ",
		img:"WWENMRAW",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Payback 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1O8ksKTs7-kxhcAHFG7l0hifpi0NCzXpAMmepNYmi-R0",
		img:"WWEPAYBACK",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Royal Rumble 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1dtd3QJgBZYfkmpPVkPzXMSAk-Lo-n8JS36SQ1o2Lzrc",
		img:"WWERR",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Summerslam 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1ibNftFixEEjhG404JwjSlVFCqjjypDjiquS7LxioOao",
		img:"WWESMS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Survivor Series 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/17kETvSD43tXDOQVeVAdnQQLtEiHNlxZd5DjZrWScYzg",
		img:"WWESS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE TLC 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1Yq5nKh9vMB9AdjzyLh_Q6r_8OVLHXOnXfzGDrJ168jw",
		img:"WWETLC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Wrestlemania 33",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1MsxAiDq1ynkedyd2n_qVvVXASgEqdQ2w2_lL2Wt-Ds4",
		img:"WWEWM33",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
  {
    id: 16,
    name: "NXT TakeOver : Wargames",
    date: 2017,
    driveLink: "https://docs.google.com/document/d/1AzduBlA-W0vRkOgUP8f5q7njzdsftU00EnqvjL6Nm9M",
    img: "NXTWARGAMES",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	{
    id: 16,
    name: "NXT TakeOver : Brooklyn III",
    date: 2017,
    driveLink: "https://docs.google.com/document/d/1MKUn_NozVigP0IRCix1wU-N2O8y_Bgg_zha0xCCqn1Y",
    img: "NXTBROOKLYN3",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	{
    id: 16,
    name: "NXT TakeOver : Orlando",
    date: 2017,
    driveLink: "https://docs.google.com/document/d/1KWc3sW43fKkwbFahoCNJbuIPtZi0aNsPmccBsN2hv1E",
    img: "NXTORLANDO",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	{
    id: 16,
    name: "NXT TakeOver : San Antonio",
    date: 2017,
    driveLink: "https://docs.google.com/document/d/1ZMcxeGCJIAHrVE4p3TT5fJiNHBdumACEQsduhZHs6eQ",
    img: "NXTSANANTONIO",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
	

	
		////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////WWE 2016/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:14,
		name: "WWE Hell In A Cell 2016",
		date: 2016,
		driveLink:"https://docs.google.com/document/d/1IZkrO5xS4KL_lXWpWnohrdOOFemoxlS_Obw6kp-uzHw",
		img:"WWESMS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE No Mercy 2016",
		date: 2016,
		driveLink:"https://docs.google.com/document/d/1RZ__7iPNg2wqZ7Sv7jerWtWDZ5-f227yw6L5QufXDyw",
		img:"WWENM",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE Survivor Series 2016",
		date: 2016,
		driveLink:"https://docs.google.com/document/d/1NQQcehCyXb_ImISFsWs8iqnYunDpa6bBwjGJ_s1nHmc",
		img:"WWESS",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
		id:14,
		name: "WWE TLC 2016",
		date: 2016,
		driveLink:"https://docs.google.com/document/d/1lPoouCEXGy13n1hyvLQoWA6KGQx11WUGUe9_dbUC_KM",
		img:"WWETLC",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
	{
    id: 16,
    name: "NXT TakeOver : Toronto",
    date: 2016,
    driveLink: "https://docs.google.com/document/d/1TEkZDEqQ8lOT0Ajpo8R5MCN6hDdfacletPBG2X94LA8",
    img: "NXTTORONTO",
    type: "WWE NXT",
    types: ["WWE", "NXT"],
	},
			////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////WWE 2015/////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:14,
		name: "WWE Royal Rumble 2015",
		date: 2015,
		driveLink:"https://docs.google.com/document/d/1vn-sTSF99odUQajj6Owhjv56BIvwa5Hlt6ZRROyf0Vc",
		img:"WWERR",
		type:"WWE PPV",
		types: ["WWE", "PPV"],
	},
		////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////LISTES ET BILANS////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:1,
		name: "4* 2019",
		date: 2019,
		driveLink:"https://docs.google.com/document/d/1smdDhBc_9jAQiACMtjM2QWOJAVKDfWTIa61euKsdj0I",
		img:"4starslist",
		type:"LISTE 4*+",
		types: ["LISTE 4*+"],
	},
	{
		id:402,
		name: "4* 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1Kcpzcil3QecaY4JGnD8FYBt8OS-qsQfBICFQlgWj-2c/edit?usp=sharings",
		img:"4starslist",
		type:"LISTE 4*+",
		types: ["LISTE 4*+"],
	},
	{
		id:403,
		name: "4* 2017",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/12Fp7ouasm_vaSRh00mRjXLFzvKYZ1zIqxPNZ5s5GyDU",
		img:"4starslist",
		type:"LISTE 4*+",
		types: ["LISTE 4*+"],
	},
	{
		id:4056,
		name: "Bilan 2018",
		date: 2018, 
		driveLink:"https://docs.google.com/document/d/1vSCsWTp9K5smYLVXKS4zIq70pfR0izGznk-pa3qdyAo",
		img:"WWEHOF",
		type:"BILAN",
		types: ["BILAN"],
	},	

	{
		id:405,
		name: "Bilan mi parcours 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/14KMNmUIqUn0-dsLLB5EcKfumtN-S5ZPgllEBpoggG-s/edit?usp=sharing",
		img:"WWEHOF",
		type:"BILAN",
		types: ["BILAN"],
	},	
	{
		id:405,
		name: "Bilan 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1W1F-w-yIf3yAcf-kvak8Xw78bJMBp12UGMbleRgP3UU",
		img:"WWEHOF",
		type:"BILAN",
		types: ["BILAN"],
	},	
	{
		id:4056,
		name: "30 Days Challenge 20/04/2019",
		date: 2019, 
		driveLink:"https://docs.google.com/document/d/1sACBiavedFXyMvDsGgJ72BwJI-SX_neP853hNwh9UWo/edit",
		img:"WWEHOF",
		type:"BILAN",
		types: ["BILAN"],
	},	
	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////MIX 2019////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:11.11,
		name: "AEW 2019",
		date: 2019,
		driveLink:"https://docs.google.com/document/d/10MT2uqplD2zaOPSKKqX4BTdpAmmAgzgwzFclMLWa5hU",
		img:"AEW",
		type:"USA",
		types: ["AEW"],
	},
	{
		id:11.1,
		name: "NJPW 2019",
		date: 2019,
		driveLink:"https://docs.google.com/document/d/17egvmGcXDYdHQ_cza7G6KEPAXxdRAatN_wI1Bt9-T6w",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW"],
	},

  {
     id: 11.1,
     name: "NJPW New Japan Cup 2019",
     date: 2019,
     driveLink: "https://docs.google.com/document/d/1XXuYAJsd7D82EMMVJkDpN5RNaRYiQohiKmqCraLYRIc",
     img: "NJC2019",
     type: "NJPW",
     types: ["NJPW"],
		},
		{
			id:8,
			name: "Joshis 2019 : STARDOM TJP Sendai Girls SEAdLINNNG",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1-ogR4LuVPyNZ0xNsx1BJ5Bp1ZgXUMekih0Oti1NPkTc",
			img:"JOSHI",
			type:"JAP",
			types: ["JOSHI"],
		},
		{
			id:2,
			name: "STARDOM 5STAR Grand Prix 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1ceuHFSA7nFJYtxKiqr6r712CBTxzNiH2442UhmTOiQs",
			img:"5SGP",
			type:"JAP",
			types: ["JOSHI"],
		},
		{
			id:10,
			name: "NJPW G1 2019 - Intro",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1LHvxxEOpVk5ziPQiNqVDzgBBZwDglNuZtlbKtotHr4s",
			img:"G129",
			type:"NJPW",
			types: ["NJPW", "G1"]
		},
		{
			id:3,
			name: "NJPW G1 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1PRkznXxQn5OvutUSQIgzx5obDhckNqRO7it7TpvsANk",
			img:"G129",
			type:"NJPW",
			types: ["NJPW", "G1"]
		},
		{
			id: 11.1,
			name: "NJPW BOSJ 2019",
			date: 2019,
			driveLink: "https://docs.google.com/document/d/1-pOcGtb0Cok8lvRbaHC8Ymy94BtRFIUDe9OdJyZeCP0",
			img: "BOSJ26",
			type: "NJPW",
			types: ["NJPW","BOSJ"],
		 },
		{
			id:6,
			name: "ROH 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1nW0yrLFZdGHBuy8-porrKkjRRLRUfaYtuBYpC61dEpk",
			img:"ROH",
			type:"USA",
			types: ["ROH"],
		},
		{
			id:6,
			name: "Indé US 2019 : EVOLVE BEYOND IWA CZW",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1ijLwa7oK7yzz2Yrjbnx7_7jq4inBDn6n9ETQLlEItmw",
			img:"INDÉ",
			type:"USA",
			types: ["INDÉ"],
		},
		{
			id:6,
			name: "Indé EU 2019 : RPW OTT wXw EVOLVE DEFIANT",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/17UnQtK22Daj0ZTRuGyZVGoiD5xIvrJQW9B2C6p3LbW4",
			img:"INDÉEU",
			type:"EUROPE",
			types: ["INDÉ"],
		},
		{
			id:7,
			name: "PROGRESS 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/19ORX9y3iBSR56kEe9uEm5rmB4OTGWwKImJiU5kiBSTs",
			img:"PROGRESS",
			type:"EUROPE",
			types: ["INDÉ", "PROGRESS"],
		},
		{
			id:3,
			name: "GCW 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1TJiZZzkKe_LymCinkkIsPCmjDKsvkpq4DA55lc1zDx4",
			img:"GCW",
			type:"USA",
			types: ["INDÉ","GCW"],
		},
		{
			id:8,
			name: "Jap 2019 : NOAH Dragon Gate DDT BJW",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1hgLb__cjRDCpTThJVH81iiwD4oo_MP-_kg4AKaN41Bo/",
			img:"JAP",
			type:"JAP",
			types: ["JAP"],
		},
		{
			id:8,
			name: "AJPW 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1oCKhqoGO_3WQ8dN7XK8QHxth-IUaS0q37bE7BrYhtT8",
			img:"AJPW",
			type:"JAP",
			types: ["JAP", "AJPW"],
		},
		{
			id:8,
			name: "AJPW Champion Carnival 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1-K6fAS5MOL_CIYvhvuslihSs6cN-y_ZwRVODvzET3kg",
			img:"CC2019",
			type:"JAP",
			types: ["JAP", "AJPW"],
		},
		{
			id:5,
			name: "PWG 2019",
			date: 2019,
			driveLink:"https://docs.google.com/document/d/1d49a9lkHsQeyudRiymU0m_II65Rd9JwDPdfaBDQsquU",
			img:"PWG",
			type:"USA",
			types: ["PWG"],
		},
	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////MIX 2018////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////


	{
		id:11,
		name: "NJPW 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1WlZ_5zcflboPzuKFzMWMruOetdFdbRRuo6S0Sy4WrAg/edit",
		img:"NJPW",
		type:"NJPW",
		types: ["NJPW"],
	},

	{
		id:12,
		name: "NJPW BOSJ 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1310NlpB9UMBDdNG_Bgd_VgP9QHCRpoM9dSynxuPDXAA/edit",
		img:"BOSJ25",
		type:"NJPW",
		types: ["NJPW", "BOSJ"],
	},
	{
		id:10,
		name: "NJPW G1 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1KoZix0UoTCiLBehLlCgN12cm0-wl3q7ATjTc0ziDO8Q/edit",
		img:"G128",
		type:"NJPW",
		types: ["NJPW", "G1"]
	},
	{
		id:8,
		name: "AJPW 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1Y7ehVVEbn5zTC6jEURL93wIFcd2cJQEthVeZfVUYvsU",
		img:"AJPW",
		type:"JAP",
		types: ["JAP", "AJPW"],
	},
	{
		id:9,
		name: "IMPACT 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1MmrjdV7u3C889Q208JQRAs2KPhG8u1wLEkX2xGdqdZQ/edit",
		img:"IMPACT",
		type:"USA",
		types: ["IMPACT"],
	},
	{
		id:8,
		name: "Jap 2018 : NOAH Dragon Gate DDT BJW",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1RuTip2OduveqHkmTTGe-pr1sa3hbUYDhdvqDkZcfBRY/edit",
		img:"JAP",
		type:"JAP",
		types: ["JAP"],
	},
	{
		id:8,
		name: "Joshis 2018 : STARDOM TJP Sendai Girls SEAdLINNNG",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1OVTwKj-SBS1fTo53zDKEIGoK496n2Iqcen77-zSb3I8",
		img:"JOSHI",
		type:"JAP",
		types: ["JOSHI"],
	},
	{
		id:7,
		name: "PROGRESS 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1xyJzOJQbHiaBjcT3-Q3oOthE5gJuLkmy9dcd25yS3Do/edit",
		img:"PROGRESS",
		type:"EUROPE",
		types: ["INDÉ", "PROGRESS"],
	},
	{
		id:6,
		name: "ROH 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1uFLYDA4G-CXz-qjODfCgZ_KE5b8XmUlvI07QhVenKgs/edit",
		img:"ROH",
		type:"USA",
		types: ["ROH"],
	},
	{
		id:5,
		name: "PWG 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1dw0jrt6UCYQcK3qkt88IC7ZCdb_2ajtr-xG0Q8CeFvI/edit",
		img:"PWG",
		type:"USA",
		types: ["PWG"],
	},
	{
		id:55,
		name: "Mex 2018 : CMLL LU AAA",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1vzqw071zu7jhHtlCruzIJ4xbq3y7D5k7pjspP3wSan8",
		img:"MEX",
		type:"MEX",
		types: ["MEX"],
	},
	{
		id:4,
		name: "WWE NXT UK 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/11SAq9SWSwlNvcqWVV0FsnALhHe3fw4xCe4b2YYmRAY4/edit",
		img:"NXTUK",
		type:"WWE NXT",
		types: ["WWE", "NXT UK"],
	},
	{
		id:3,
		name: "Indé US 2018 : EVOLVE IWA CZW ALL IN",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1ZjOGVs-pq62lqF-67taJqPyCG152RGPKMqJ7GFE0WXE/edit",
		img:"INDÉ",
		type:"USA",
		types: ["INDÉ"],
	},
	{
		id:6,
		name: "Indé EU 2018 : RPW OTT wXw EVOLVE DEFIANT",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1lVjJbIaMHcaqZILSoxoyQ6tYiK-qlS6zZmgn2SN7GkE",
		img:"INDÉEU",
		type:"EUROPE",
		types: ["INDÉ"],
	},
	{
		id:3,
		name: "GCW 2018",
		date: 2018,
		driveLink:"https://docs.google.com/document/d/1AgVxf3mlt5hPa7JK-AU9ks3xUiObkkqZyYRJsZ6krdU",
		img:"GCW",
		type:"USA",
		types: ["INDÉ","GCW"],
	},
	////////////////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////MIX 2017////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////
	{
		id:20171,
		name: "NJPW G1 2017",
		date: 2017,
		driveLink:"https://docs.google.com/document/d/1wwBwP2WQfpLfIMTlFJbEXW5EDk7uiP9Rr6r3tdQlIUA",
		img:"G127",
		type:"NJPW",
		types: ["NJPW", "G1"]
	},
]
