import { Review } from 'src/app/wrestling/review';

export const NEWYEARTEMPLATE: Review[] = [

	{
		id: 202001,
		name: "AEW 2020",
		date: 2020,
		driveLink: "",
		img: "AEW",
		type: "USA",
		types: ["AEW"],
	},
	{
		id: 202002,
		name: "AJPW 2020",
		date: 2020,
		driveLink: "",
		img: "AJPW",
		type: "JAP",
		types: ["JAP", "AJPW"],
	},
	{
		id: 202003,
		name: "DDT 2020",
		date: 2020,
		driveLink: "",
		img: "DDT",
		type: "JAP",
		types: ["JAP", "DDT"],
	},
	{
		id: 202004,
		name: "GCW 2020",
		date: 2020,
		driveLink: "",
		img: "GCW",
		type: "USA",
		types: ["INDÉ", "GCW"],
	},
	{
		id: 202005,
		name: "IMPACT 2020",
		date: 2020,
		driveLink: "",
		img: "IMPACT",
		type: "USA",
		types: ["IMPACT"],
	},
	{
		id: 202006,
		name: "Indé US 2020 : EVOLVE BEYOND CZW",
		date: 2020,
		driveLink: "",
		img: "INDÉ",
		type: "USA",
		types: ["INDÉ"],
	},
	{
		id: 202007,
		name: "Indé EU 2020 : RPW OTT wXw EVOLVE",
		date: 2020,
		driveLink: "",
		img: "INDÉEU",
		type: "EUROPE",
		types: ["INDÉ"],
	},
	{
		id: 202008,
		name: "Jap 2020 : NOAH Dragon Gate BJW",
		date: 2020,
		driveLink: "",
		img: "JAP",
		type: "JAP",
		types: ["JAP"],
	},
	{
		id: 202009,
		name: "Joshis 2020 : TJP Sendai Girls SEAdLINNNG",
		date: 2020,
		driveLink: "",
		img: "JOSHI",
		type: "JAP",
		types: ["JOSHI"],
	},
	{
		id: 202010,
		name: "Mex 2020 : CMLL LU AAA",
		date: 2020,
		driveLink: "",
		img: "MEX",
		type: "MEX",
		types: ["MEX"],
	},
	{
		id: 202011,
		name: "NJPW 2020",
		date: 2020,
		driveLink: "",
		img: "NJPW",
		type: "NJPW",
		types: ["NJPW"],
	},
	{
		id: 202013,
		name: "PROGRESS 2020",
		date: 2020,
		driveLink: "",
		img: "PROGRESS",
		type: "EUROPE",
		types: ["INDÉ", "PROGRESS"],
	},
	{
		id: 202014,
		name: "PWG 2020",
		date: 2020,
		driveLink: "",
		img: "PWG",
		type: "USA",
		types: ["PWG"],
	},
	{
		id: 202015,
		name: "ROH 2020",
		date: 2020,
		driveLink: "",
		img: "ROH",
		type: "USA",
		types: ["ROH"],
	},
	{
		id: 202016,
		name: "STARDOM",
		date: 2020,
		driveLink: "",
		img: "JOSHI",
		type: "JAP",
		types: ["JOSHI"],
	},
]